json.extract! @customer, 
              :id,
              :first_name, 
              :last_name, 
              :email_address, 
              :phone_number, 
              :street_address, 
              :zip_code, 
              :apt_number, 
              :business_id